DROP DATABASE IF EXISTS PIECES;
CREATE DATABASE PIECES;
USE PIECES;

CREATE TABLE IF NOT EXISTS Pieces(
CodeID INT NOT NULL,
Name VARCHAR(40) NOT NULL,
PRIMARY KEY(CodeID));

CREATE TABLE IF NOT EXISTS Providers(
CodeID VARCHAR(40) NOT NULL,
Name TEXT NOT NULL,
PRIMARY KEY(CodeID));

CREATE TABLE IF NOT EXISTS Provides(
Piece INT,
Provider VARCHAR(40) NOT NULL,
Price INT NOT NULL,
PRIMARY KEY(Piece, Provider),
FOREIGN KEY (Piece) REFERENCES Pieces(CodeID),
FOREIGN KEY (Provider) REFERENCES Providers(CodeID)
);

